### ISSUE TITLE
Implement named and default exports

### ISSUE THREAD

**Issue by paxperscientiam** [badzong/meshspin.js#3]
E.G. https://hackernoon.com/import-export-default-require-commandjs-javascript-nodejs-es6-vs-cheatsheet-different-tutorial-example-5a321738b50f

This would make importing code easier per es6. Also, I'm thinking the default import/export corresponds to the constructor `MeshSpin` and named ones would, conceivably, correspond to predefined (for instance) polyhedra.

Feel free to assign this one to me!

**Comment by badzong** [comment]
Thanks for pointing that out. Just go ahead and supply your PullRequest :)

**Comment by paxperscientiam** [comment]
Per the OP, the PR I submitted includes a single named class export ("MeshSpin"). PR #4 

EDIT: I think this can be closed
