### ISSUE TITLE
Tag release / update documentation

### ISSUE THREAD

**Issue by paxperscientiam** [badzong/meshspin.js#8]
I know you said that you'd like to update the docs before tagging a new release. What do you think of moving docs to repo?

**Comment by badzong** [comment]
I tried to update the docs. But I use MeshSpin with my own Makefile based bundler which does not work with ES6 Modules. With the latest commit I removed FuseBox from the dependencies. However using it as a module in a FuseBox environment should still work.

The "dist" folder now contains an ES6 module and a CommonJS module with a minified version created through the Makefile.

Does "dist/meshspin.es6.js" work for your environment?
